name: Deploy current version to staging/production environment.
on:
  push:
    branches: [staging, main]

jobs:
  setup:
    name: Setup project.
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      - name: Build app
        run: pnpm run build
  deploy-preview:
    name: Deploy preview to VPS.
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Deploy preview
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: pnpm run staging
      - name: Deploy production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: pnpm run deploy
